/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Model.DatosNotificacion;
import Model.Time;
import java.awt.Color;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Pri extends javax.swing.JFrame {

    private TrayIcon trayIcon;
    private SystemTray systemtray;
    private ImageIcon imagenIcon;
    private static String DatoNotificacion;

    public String getDatoNotificacion() 
    {
        return DatoNotificacion;
    }

    public void setDatoNotificacion(String DatoNotificacion1) 
    {
        Pri.DatoNotificacion = DatoNotificacion1;
    }

    /**
     * Creates new form Pri
     */
    public Pri() {
        ///para poner icono a la aplicacion (this.getClass().getRe... busca en el proyecto y pone la imagen)
        imagenIcon = new ImageIcon(this.getClass().getResource("/Imagenes/Alarma2.png"));
        //con this.set ...  se ubica la imagen en el frame.
        this.setIconImage(imagenIcon.getImage());
        //instanciarTray();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTareaPendiente = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTiempoenHoras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTiempoenMinutos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTiempoenSegundos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("Primer Pano");
        Popup.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recordatorios");
        setBackground(new java.awt.Color(0, 204, 51));
        setResizable(false);

        txtTareaPendiente.setColumns(20);
        txtTareaPendiente.setRows(5);
        jScrollPane1.setViewportView(txtTareaPendiente);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Ingrese Tarea Pendiente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ingrese el tiempo e Iniciar.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel3.setText("En Minutos, Ejemplo :15 = 15 minutos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Temporizador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(5, 5, 5))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("HORA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 32, -1, -1));

        txtTiempoenHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoenHoras.setText("0");
        txtTiempoenHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoenHorasKeyTyped(evt);
            }
        });
        jPanel1.add(txtTiempoenHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 29, 20, -1));

        jLabel5.setText("MINUTOS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 61, -1, -1));

        txtTiempoenMinutos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoenMinutos.setText("0");
        txtTiempoenMinutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoenMinutosKeyTyped(evt);
            }
        });
        jPanel1.add(txtTiempoenMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 58, 20, -1));

        jLabel6.setText("SEGUNDOS:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 87, -1, -1));

        txtTiempoenSegundos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoenSegundos.setText("0");
        txtTiempoenSegundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoenSegundosKeyTyped(evt);
            }
        });
        jPanel1.add(txtTiempoenSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 84, 20, -1));

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void validarDatosdeVentaPri() 
    {
        
        try {
                if ("".equals(txtTiempoenHoras.getText())
                    || "".equals(txtTiempoenMinutos.getText())
                    || "".equals(txtTiempoenSegundos.getText())) 
                {

                    JOptionPane.showMessageDialog(null, "¡ HA DEJADO CAMPOS EN BLANCO !");
                } 
                else 
                {
                //llamada a metodo para enviar datos y recibir
                EnviarDatosYRecivirDatosNotificacion();
                //se llama el metodo tiempo para tomar tiempo ingresado para la notificacion y lo envia a Time
                ObtenerTiempoIngresadoYEnviarlo();
                }

            } catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(null, "Error al validar datos ingresados(POR FAVOR VERIFIQUE DATOS INGRESADOS): " + e.getMessage());
                }
    }

    public void ObtenerTiempoIngresadoYEnviarlo() 
    {
        ///instancia del tiempo para que espere el tiempo ingresado por el usuario
        Model.Time tiempo = new Time();
        try 
        {   
           //se envian los datos de hora, minutos y tiempo
            tiempo.Tiempo(txtTiempoenHoras.getText(), txtTiempoenMinutos.getText(), txtTiempoenSegundos.getText());

        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, "Error al validar datos ingresados(POR FAVOR VERIFIQUE DATOS INGRESADOS): " + ex.getMessage());
        }
    }

    public void EnviarDatosYRecivirDatosNotificacion() 
    {
        Model.DatosNotificacion pr = new DatosNotificacion();
        //se lleva lo que esta en el txtTarea con set a la variable
        pr.setDatonotificacion(txtTareaPendiente.getText());
        ///se crea instancia del objeto de la pantalla notificacion, y se le envia el dato de tarea pendiente
        Vista.Notificacion run = new Notificacion();
        //con el get se envia el dato al metodo
        run.DatoAMostar(pr.getDatonotificacion());
        //para cerrar formulario actual luego de enviar el dato
        dispose();
        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        validarDatosdeVentaPri();
    }//GEN-LAST:event_jButton1ActionPerformed

    //para validar que el txt solo reciba numeros y no letras
    private void txtTiempoenHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoenHorasKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) 
        {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa Solo Numeros");

        }

    }//GEN-LAST:event_txtTiempoenHorasKeyTyped
    //para validar que el txt solo reciba numeros y no letras
    private void txtTiempoenMinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoenMinutosKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) 
        {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa Solo Numeros");

        }
    }//GEN-LAST:event_txtTiempoenMinutosKeyTyped
    //para validar que el txt solo reciba numeros y no letras
    private void txtTiempoenSegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoenSegundosKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) 
        {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa Solo Numeros");

        }
    }//GEN-LAST:event_txtTiempoenSegundosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pri().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Popup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTareaPendiente;
    private javax.swing.JTextField txtTiempoenHoras;
    private javax.swing.JTextField txtTiempoenMinutos;
    private javax.swing.JTextField txtTiempoenSegundos;
    // End of variables declaration//GEN-END:variables
}
